### ISSUE TITLE
What is the dataset used?

### ISSUE THREAD

**Issue by vikramrathore1799** [samuelmat19/image2source-tf2#2]
Could you provide the link of the dataset used. I'm getting the following error:-
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/pix2code'

**Comment by samuelmat19** [comment]
@vikramrathore1799 firstly, sorry for the late reply. The dataset is derived from https://github.com/tonybeltramelli/pix2code . I will write more about it later in the README. Thanks for the feedback too!

**Comment by samuelmat19** [comment]
@vikramrathore1799 firstly, sorry for the late reply. The dataset is derived from https://github.com/tonybeltramelli/pix2code . I will write more about it later in the README. Thanks for the feedback!
